server:
  port: 9527
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能 利用微服务名进行路由
          enabled: true
      routes:
          # 路由id
        - id: payment_routh
          # 匹配后提供的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-hystrix-service
          predicates:
            # 断言 路径相匹配的进行路由
            - Path=/payment/get/**
            # 条件 在某时间之后 规则才被激活
#            - After=
#            - Before=
#            - Between=
            # 带cookie 才可以访问 key value
#            - Cookie=username,test
            # 带请求头 后面正则
#            - Header=X-Request-Id, \d+
            # 请求方法
#            - Method=GET
            # 有参数 并且value是整数
#            - Query=username, \d+





        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-hystrix-service
          predicates:
            - Path=/payment/cir/**


eureka:
  instance:
    hostname: cloud-gatewat-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
