server:
  port: 80


eureka:
  client:
    fetch-registry: true
    # 注册eureka
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-feign-hystrix-order80
feign:
  hystrix:
    enabled: true
