server:
  port: 80
spring:
  application:
    name: cloud-order80

eureka:
  client:
    # 注册eureka
    register-with-eureka: true
    # 抓取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
